### ISSUE TITLE
您好，原意复述你有研究么？能不能出个demo

### ISSUE THREAD

**Issue by jobsfan** [zhaozhengcoder/Machine-Learning#1]
您好！

最近头儿给我了一个case，说是让我弄伪原创，大意就是输入几篇相同意思的新闻，然后输出得到一篇不同的，但是意思相同的新闻。网上找了很多，一般都是自己写诗写文章，但是内容意思不可控。这个你能帮帮忙么？

**Comment by zhaozhengcoder** [comment]
感觉这是一个很有意思的东西，但是，小弟不才，最近刚刚工作，要学习和熟悉的东西太多了，没有时间做这个，不好意思。
