### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by hjy2588818** [zhaozhengcoder/Machine-Learning#2]
请教一下，一篇文章，由很多句子组成段落，由段落组成文章。RNN的方式仿写需要大量的学习训练。如果一篇文章由语义分析后，整理出来很多相关的句子，那么这些句子还能组成可读性较高的文章吗

**Comment by zhaozhengcoder** [comment]
感觉你说的这个任务还是比较困难的，我猜测一下，如果你有海量的数据或者你的model厉害，也许会有一些效果。
